"""update meta nad file model

Revision ID: 8bb4dc43ebb4
Revises: 
Create Date: 2021-04-20 17:48:04.969258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb4dc43ebb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('CREATEDON', sa.DateTime(), nullable=False),
    sa.Column('UPDATEON', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('CREATEDON', sa.DateTime(), nullable=False),
    sa.Column('UPDATEON', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('meta')
    # ### end Alembic commands ###
