version: "3.9"

volumes:
    app_data:
        external: true

networks:
    default:
        external:
            name: mediaserver-network

services:
    mediaserver:
        image: mediaserver
        build:
            context: .
            dockerfile: base.dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ../..:/usr/user/app
        command: "exit 0"

    mediaserver-mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: database
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
        depends_on:
            - mediaserver-adminer
        volumes:
            - ../mysql:/etc/mysql/conf.d

    mediaserver-adminer:
        image: adminer:latest
        ports:
            - 8080:8080

